name: Slither

on: [push, pull_request]

jobs:
  slither:
    name: Slither Analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ["14.x"]
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v2
      - name: Nodejs 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          check-latest: true

      - name: Cache compiler installations
        uses: actions/cache@v2
        with:
          path: |
            ~/.solcx
            ~/.vvm/vyper-*
          key: ${{ runner.os }}-compiler-cache

      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set pip cache directory path
        id: pip-cache-dir-path
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Restore pip cache
        uses: actions/cache@v2
        id: pip-cache
        with:
          path: |
            ${{ steps.pip-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
            ${{ runner.os }}-pip-

      - name: Install python dependencies
        run: pip install -r requirements-dev.txt

      - name: Compile brownie
        run: brownie compile
        id: compile

      - name: Run Slither
        uses: crytic/slither-action@v0.1.0
        continue-on-error: true
        id: slither
